services:
  server:
    build: ./server
    ports:
      - 5050:5000
  mongodb:
    image: mongo
  client:
    build: ./client
    ports:
      - 8080:3000
    volumes:
      - ./client/src/:/app/src/
